### PR TITLE
Added popup Syntax Selector

### PR DESCRIPTION
**Pull request by Aecasorg**
In pasteview, a syntax selector picker has been added. It defaults to language set in options menu. If there's not a matching language that Hightlightr supports then it is set to let Highlightr automatically choose. 

Partially fixed the background bug. On an iPhone SE the background image starts lower so you see top edge, however, I don't actually know if this will actually be like this on an actual phone. Not tested. 

Changed the order around for main VC buttons. More logical perhaps but looks slightly worse on an iPhone SE. Should we keep or change back?

Let me know if you want any changes to the above. 

Enjoy!
Henrik

### CODE REVIEW

**Comment by jonluca** [comment]
Looks great! Thanks!

I’m open to suggestions on how to fix the scrolling background. We could either try something completely new and different, or try to fix it everywhere. Did you have anything in mind?

**Comment by Aecasorg** [comment]
I think I fixed the issue that you had or at least the one you mentioned on GitHub. 

What phone are you using when you test? What issues do you see currently with the background?

I’ve got an iPhone SE so I’ll test with the actual device and see if there are any issues. 

I’d prefer to stick with scrolling background you set up as I quite like that, so I’ll see if I can fix it but I need to know exactly what issues you see so I hopefully can replicate them here. 

Henrik

**Comment by Aecasorg** [comment]
Ok, I can’t test it on my phone since I’m not in the “development team”. No worries. Maybe you can do the actual device testing? 

Cheers!

**Comment by jonluca** [comment]
Looks good to me! Just tested it, it all works.

Also, can you not test it in the simulator? You should be able to build locally even without an Apple Dev account. 

I also went through and reformatted some stuff just slightly, to maintain a more consistent style. You can see the commit [here](https://github.com/jonluca/PasteBinApp/commit/175ce6f21328aa4c2318b012324879a47035f4e7)

Thanks again!

**Comment by Aecasorg** [comment]
You’re welcome!

Yes, I always test in the simulators. I usually test with iPhone SE, 8 and X simulators in order to cover most variations. Simulators are not perfect so there are still issues that can come up when you use the app on a real device, which is now what has happened it seems. All the simulations worked however when I now downloaded the app from the App Store the Syntax Highlighter does not work on my iPhone SE. I’m not sure now how to solve this since I can’t test on my device. I’ll download your newest commit and see it I can replicate the issue. 

Nice! It is always good to clean up code now and then :) 

Oh, one thing. Could I ask a favour from you at some point in future? Very simple, but it could help me when I look for work later this year. 

Henrik

**Comment by Aecasorg** [comment]
One more thing…

Do you know anyone with an iPhone X? In the simulator I get the error "Bad API request, invalid api_paste_format” when trying to send a paste to pastebin.com but again, simulators don’t always correspond entirely to real devices so it could be a non-issue. My iPhone X simulator behaves different from the other sims so I don’t know if there’s difference there. Technically there should not be a difference since they run the same OS. Is there anyone you know that could test this for us?

On an separate note I have been thinking. I like your quick paste function on the main screen on the app and I would like to extend it by using 3DTouch so you can get an option to do it from the home screen icon instead of entering the app and then do it. How does that sound?

Henrik

**Comment by Aecasorg** [comment]
OK, I’m sorry. I did not realise you had already implemented 3D Touch. Great! So just ignore my suggestion… :)

Henrik

**Comment by jonluca** [comment]
Yes, I have the iPhone X and I'm running into that issue as well. I'm looking into it. I've also been getting some random crashes with typing in user and switching syntaxes, not really sure what it is. I'm pretty busy this week but I'll try to take a look soon.

And sure! What favor did you need?

**Comment by jonluca** [comment]
Hmm odd the error isn't happening for me anymore. Not sure what's up.

**Comment by Aecasorg** [comment]
Hmm… Keep trying it out and let me know what errors you get (if you get any), so I can investigate. Thanks! 

Favour? Well, it is easy. If you happen to have a LinkedIn account, if you could endorse some of my relevant skills it would help greatly. It is not urgent though. 

Henrik

**Pull request merged**
