### PR TITLE
Added syntax search in Options Menu

### PR DESCRIPTION
**Pull request by Aecasorg**
Added textfield search with drop-down suggestions to Options Menu Syntax selection. Automatically scrolls to selected syntax.

### CODE REVIEW

**Comment by Aecasorg** [comment]
One thing... Since we have two different ways of selecting syntax, should we drop one and stick with one way of doing it for the sake of continuity/UX or keep it as it is? If we drop one, which way do you want to keep? I'm happy either way.

**Comment by Aecasorg** [comment]
Thanks!

**Comment by jonluca** [comment]
I'm not sure, what do you think? I agree that two ways is bad UX. We should just pick one.

Also, I'm not sure about that weird bad api request bug. The api found here https://pastebin.com/api lists all the valid syntaxes. I've done some simple debugging but couldn't get it to fail. What's a language that fails for you?

**Comment by Aecasorg** [comment]
Yup. Personally for me, both work. The list (options menu one) gives better overview whereas the picker (pasterview popup) is perhaps easier on the eye. Not sure is better.

 Do you know anyone who uses the app? If you do, ask them which selector they find easier to use. It would be interesting so see what actual users think and then choose based on that. Not many people for me ask here in rural France, the local farmers still use button phones! 😆

**Pull request merged**
